// Auto-generated daily intelligence feed — 2026-06-16 20:50 IST
// ⚠️ Do not edit manually. Regenerated by scripts/generate-feed.js

export interface DailyFeed {
  generatedAt: string;
  stats: {
    date: string;
    lastUpdated: string;
    newEvents: number;
    newAlerts: number;
    newActivityItems: number;
    alertsBySeverity: { critical: number; high: number; medium: number; low: number };
  };
  entities: any[];
  alerts: any[];
  activity: any[];
}

export const dailyFeed: DailyFeed = {
  "generatedAt": "2026-06-16T15:20:56.299Z",
  "stats": {
    "date": "2026-06-16",
    "lastUpdated": "2026-06-16 20:50",
    "newEvents": 10,
    "newAlerts": 2,
    "newActivityItems": 5,
    "alertsBySeverity": {
      "critical": 0,
      "high": 1,
      "medium": 1,
      "low": 0
    }
  },
  "entities": [
    {
      "id": "DE-FA2A27",
      "type": "event",
      "name": "Movement Tracked — Meera Kapoor",
      "properties": {
        "person": "Meera Kapoor",
        "vehicle": "UP-16-T-9054",
        "destination": "Cyber City, Gurugram",
        "method": "ANPR camera",
        "confidence": "90%"
      },
      "location": {
        "lat": 28.4595,
        "lng": 77.0266,
        "address": "Cyber City, Gurugram"
      },
      "timestamp": "2026-06-16T14:48:03.810Z",
      "riskScore": 83,
      "tags": [
        "movement-track",
        "daily-feed"
      ],
      "links": [
        "P-006"
      ]
    },
    {
      "id": "DE-1BB348",
      "type": "event",
      "name": "Movement Tracked — Anita Sharma",
      "properties": {
        "person": "Anita Sharma",
        "vehicle": "UP-16-T-9054",
        "destination": "Dwarka, Delhi",
        "method": "ANPR camera",
        "confidence": "66%"
      },
      "location": {
        "lat": 28.5921,
        "lng": 77.046,
        "address": "Dwarka, Delhi"
      },
      "timestamp": "2026-06-16T14:39:49.340Z",
      "riskScore": 37,
      "tags": [
        "movement-track",
        "daily-feed"
      ],
      "links": [
        "P-003"
      ]
    },
    {
      "id": "DE-6A1210",
      "type": "event",
      "name": "Movement Tracked — Suresh Kalmadi",
      "properties": {
        "person": "Suresh Kalmadi",
        "vehicle": "DL-3C-AX-7842",
        "destination": "Laxmi Nagar, Delhi",
        "method": "toll plaza",
        "confidence": "65%"
      },
      "location": {
        "lat": 28.6304,
        "lng": 77.2773,
        "address": "Laxmi Nagar, Delhi"
      },
      "timestamp": "2026-06-16T15:18:07.901Z",
      "riskScore": 33,
      "tags": [
        "movement-track",
        "daily-feed"
      ],
      "links": [
        "P-007"
      ]
    },
    {
      "id": "DE-0FB77A",
      "type": "event",
      "name": "Movement Tracked — Vikram Malhotra",
      "properties": {
        "person": "Vikram Malhotra",
        "vehicle": "UP-16-T-9054",
        "destination": "Connaught Place, New Delhi",
        "method": "toll plaza",
        "confidence": "89%"
      },
      "location": {
        "lat": 28.6315,
        "lng": 77.2167,
        "address": "Connaught Place, New Delhi"
      },
      "timestamp": "2026-06-16T09:53:47.368Z",
      "riskScore": 50,
      "tags": [
        "movement-track",
        "daily-feed"
      ],
      "links": [
        "P-001"
      ]
    },
    {
      "id": "DC-1C843D",
      "type": "communication",
      "name": "Intercepted WHATSAPP — Meera → Farhan",
      "properties": {
        "type": "WhatsApp",
        "from": "Meera Kapoor",
        "to": "Farhan Siddiqui",
        "duration": "7m 58s",
        "keyPhrase": "\"meet at the usual place\"",
        "classification": "RESTRICTED"
      },
      "timestamp": "2026-06-16T12:11:04.236Z",
      "riskScore": 80,
      "tags": [
        "intercept",
        "daily-feed"
      ],
      "links": [
        "P-006",
        "P-005"
      ]
    },
    {
      "id": "DC-3B1BD5",
      "type": "communication",
      "name": "Intercepted SIGNAL — Farhan → Deepak",
      "properties": {
        "type": "Signal",
        "from": "Farhan Siddiqui",
        "to": "Deepak Tyagi",
        "duration": "1m 46s",
        "keyPhrase": "\"route changed — use backup\"",
        "classification": "SECRET"
      },
      "timestamp": "2026-06-16T14:27:17.980Z",
      "riskScore": 65,
      "tags": [
        "intercept",
        "daily-feed"
      ],
      "links": [
        "P-005",
        "P-004"
      ]
    },
    {
      "id": "DC-E55240",
      "type": "communication",
      "name": "Intercepted WHATSAPP — Vikram → Suresh",
      "properties": {
        "type": "WhatsApp",
        "from": "Vikram Malhotra",
        "to": "Suresh Kalmadi",
        "duration": "5m 21s",
        "keyPhrase": "\"the package is ready\"",
        "classification": "SECRET"
      },
      "timestamp": "2026-06-16T12:09:16.060Z",
      "riskScore": 55,
      "tags": [
        "intercept",
        "daily-feed"
      ],
      "links": [
        "P-001",
        "P-007"
      ]
    },
    {
      "id": "DF-4B6786",
      "type": "financial",
      "name": "Transaction Flag — ₹45L",
      "properties": {
        "amount": "₹45L",
        "method": "RTGS",
        "linkedTo": "Meera Kapoor",
        "bank": "SBI",
        "flag": "STR Filed"
      },
      "location": {
        "lat": 28.63,
        "lng": 77.32,
        "address": "Ghazipur Border, Delhi-UP"
      },
      "timestamp": "2026-06-16T00:02:57.216Z",
      "riskScore": 80,
      "tags": [
        "financial-monitoring",
        "daily-feed"
      ],
      "links": [
        "P-006"
      ]
    },
    {
      "id": "DF-FDC30D",
      "type": "financial",
      "name": "Transaction Flag — ₹2.5Cr",
      "properties": {
        "amount": "₹2.5Cr",
        "method": "RTGS",
        "linkedTo": "Deepak Tyagi",
        "bank": "ICICI",
        "flag": "STR Filed"
      },
      "location": {
        "lat": 28.4595,
        "lng": 77.0266,
        "address": "Cyber City, Gurugram"
      },
      "timestamp": "2026-06-16T04:14:32.036Z",
      "riskScore": 57,
      "tags": [
        "financial-monitoring",
        "daily-feed"
      ],
      "links": [
        "P-004"
      ]
    },
    {
      "id": "DF-8E3948",
      "type": "financial",
      "name": "Transaction Flag — ₹32L",
      "properties": {
        "amount": "₹32L",
        "method": "RTGS",
        "linkedTo": "Vikram Malhotra",
        "bank": "HDFC",
        "flag": "CTR Filed"
      },
      "location": {
        "lat": 28.5244,
        "lng": 77.2066,
        "address": "Saket, New Delhi"
      },
      "timestamp": "2026-06-16T12:11:10.963Z",
      "riskScore": 56,
      "tags": [
        "financial-monitoring",
        "daily-feed"
      ],
      "links": [
        "P-001"
      ]
    }
  ],
  "alerts": [
    {
      "id": "DA-6FA039",
      "severity": "medium",
      "title": "Border Checkpoint Alert — Suspicious Crossing",
      "description": "ANPR system flagged vehicle at Ghazipur border. Cargo manifest mismatch. Driver identity unverified.",
      "timestamp": "2026-06-16T13:33:57.907Z",
      "location": {
        "lat": 28.63,
        "lng": 77.32
      },
      "entityId": "P-006",
      "acknowledged": false
    },
    {
      "id": "DA-3FCA5F",
      "severity": "high",
      "title": "Dark Web Marketplace Listing — Delhi NCR",
      "description": "Crawler detected new listing matching contraband profile. Seller signature matches known operation.",
      "timestamp": "2026-06-16T10:21:40.530Z",
      "location": {
        "lat": 28.6139,
        "lng": 77.209
      },
      "entityId": "P-003",
      "acknowledged": false
    }
  ],
  "activity": [
    {
      "time": "17:24",
      "event": "Cyber cell dashboard: new phishing domain registered targeting Siddiqui Imports LLC",
      "severity": "medium"
    },
    {
      "time": "10:17",
      "event": "Cyber cell dashboard: new phishing domain registered targeting Delhi Infrastructure Corp",
      "severity": "low"
    },
    {
      "time": "02:31",
      "event": "Vehicle DL-3C-AX-7842 tracked at toll plaza — Laxmi Nagar, Delhi",
      "severity": "medium"
    },
    {
      "time": "18:08",
      "event": "OSINT alert: social media post matches geolocation trigger — Dwarka",
      "severity": "high"
    },
    {
      "time": "09:14",
      "event": "SATCOM intercept: encrypted burst transmission detected — Gurugram cell",
      "severity": "high"
    }
  ]
};
